In [1]:
import pandas as pd 
import os
feature_name_dict = {'Sidewalk width': 'sidewalk_width',
                        'Pedestrian density': 'pedestrian_density',
                        'Density of street furniture (e.g. garbage, poles)': 'street_furniture_density',
                        'Sidewalk / Surface roughness': 'sidewalk_roughness',
                        'Surface condition': 'surface_condition',
                        'Wireless communication infrastructure (e.g. 5G, IoT, Wi-Fi)': 'communication_infrastructure',
                        'Slope gradient (i.e. elevation change)': 'slope_gradient',
                        'Proximity to charging stations': 'charging_station_proximity',
                        'Local attitudes towards robots': 'local_attitudes',
                        'Curb ramp availability': 'curb_ramp_availability',
                        'Weather conditions': 'weather_conditions',
                        'Crowd dynamics - purpose with which people navigate in the space': 'crowd_dynamics',
                        'Traffic management systems': 'traffic_management',
                        'Surveillance coverage (CCTV)': 'surveillance_coverage',
                        'Zoning laws and regulation': 'zoning_laws',
                        'Bike lane availability': 'bike_lane_availability',
                        'Street lighting': 'street_lighting',
                        'Existence of shade (e.g., trees)': 'shade_availability',
                        'GPS signal strength': 'gps_signal_strength',
                        'Pedestrian flow': 'pedestrian_flow',
                        'Bicycle traffic': 'bicycle_traffic',
                        'Vehicle traffic': 'vehicle_traffic',
                        'Existence of detailed digital maps of the area': 'digital_map_existence',
                        'Intersection safety': 'intersection_safety'}

In [ ]:
all_weights = pd.read_csv("all_weights.csv", index_col=0)
industry_weights = pd.read_csv("industry_weights.csv", index_col=0)
academia_weights = pd.read_csv("academia_weights.csv", index_col=0)
other_weights = pd.read_csv("other_weights.csv", index_col=0)
trashbot_weights = pd.read_csv("trashbot_weights.csv", index_col=0)

In [3]:
# reverse the dictionary
feature_name_dict = {v: k for k, v in feature_name_dict.items()}
feature_name_dict

{'sidewalk_width': 'Sidewalk width',
 'pedestrian_density': 'Pedestrian density',
 'street_furniture_density': 'Density of street furniture (e.g. garbage, poles)',
 'sidewalk_roughness': 'Sidewalk / Surface roughness',
 'surface_condition': 'Surface condition',
 'communication_infrastructure': 'Wireless communication infrastructure (e.g. 5G, IoT, Wi-Fi)',
 'slope_gradient': 'Slope gradient (i.e. elevation change)',
 'charging_station_proximity': 'Proximity to charging stations',
 'local_attitudes': 'Local attitudes towards robots',
 'curb_ramp_availability': 'Curb ramp availability',
 'weather_conditions': 'Weather conditions',
 'crowd_dynamics': 'Crowd dynamics - purpose with which people navigate in the space',
 'traffic_management': 'Traffic management systems',
 'surveillance_coverage': 'Surveillance coverage (CCTV)',
 'zoning_laws': 'Zoning laws and regulation',
 'bike_lane_availability': 'Bike lane availability',
 'street_lighting': 'Street lighting',
 'shade_availability': 'Existence of shade (e.g., trees)',
 'gps_signal_strength': 'GPS signal strength',
 'pedestrian_flow': 'Pedestrian flow',
 'bicycle_traffic': 'Bicycle traffic',
 'vehicle_traffic': 'Vehicle traffic',
 'digital_map_existence': 'Existence of detailed digital maps of the area',
 'intersection_safety': 'Intersection safety'}

In [4]:
all_weights.index = all_weights.index.map(feature_name_dict)
industry_weights.index = industry_weights.index.map(feature_name_dict)
academia_weights.index = academia_weights.index.map(feature_name_dict)
other_weights.index = other_weights.index.map(feature_name_dict)
trashbot_weights.index = trashbot_weights.index.map(feature_name_dict)

In [5]:
# merge all the weights with one column for each 
all_weights = all_weights.rename(columns={'Weight': 'All'})
industry_weights = industry_weights.rename(columns={'Weight': 'Industry'})
academia_weights = academia_weights.rename(columns={'Weight': 'Academia'})
other_weights = other_weights.rename(columns={'Weight': 'Other'})
trashbot_weights = trashbot_weights.rename(columns={'Weight': 'Trashbot'})

In [6]:
# merge 
all_weights = all_weights.merge(industry_weights, left_index=True, right_index=True, how='outer')
all_weights = all_weights.merge(academia_weights, left_index=True, right_index=True, how='outer')
all_weights = all_weights.merge(other_weights, left_index=True, right_index=True, how='outer')
all_weights = all_weights.merge(trashbot_weights, left_index=True, right_index=True, how='outer')

In [7]:
# sort by 'All' 
all_weights = all_weights.sort_values(by='All', ascending=False).reset_index()
all_weights

,Feature,All,Industry,Academia,Other,Trashbot
0,Pedestrian density,0.072944,0.057084,0.073673,0.097634,0.119692
1,Crowd dynamics - purpose with which people nav...,0.063126,0.048534,0.069753,0.057084,0.099848
2,Pedestrian flow,0.062957,0.071824,0.064218,0.059401,NaN
3,Surface condition,0.057289,0.076393,0.054884,0.018299,0.101684
4,Intersection safety,0.057254,0.056413,0.054183,0.031198,NaN
5,"Density of street furniture (e.g. garbage, poles)",0.053924,0.053436,0.056586,0.043476,0.083682
6,Sidewalk width,0.053274,0.053288,0.054794,0.051594,0.083182
7,Weather conditions,0.051378,0.046098,0.062341,0.023552,NaN
8,Wireless communication infrastructure (e.g. 5G...,0.048969,0.053567,0.036748,0.097455,0.068942
9,Curb ramp availability,0.048322,0.028036,0.051506,0.039108,0.081910
10,Sidewalk / Surface roughness,0.041455,0.049036,0.039435,0.037303,0.052740
11,GPS signal strength,0.040063,0.049756,0.033960,0.048967,0.059464
12,Local attitudes towards robots,0.039427,0.040155,0.040333,0.070816,NaN
13,Existence of detailed digital maps of the area,0.038870,0.052096,0.037339,0.037380,0.060649
14,Traffic management systems,0.038201,0.050997,0.037505,0.035007,NaN
15,Vehicle traffic,0.037391,0.046769,0.039379,0.027057,NaN
16,Slope gradient (i.e. elevation change),0.037232,0.020518,0.042564,0.033202,0.062835
17,Zoning laws and regulation,0.034909,0.023850,0.038567,0.067801,NaN
18,Street lighting,0.026465,0.044629,0.021106,0.008426,NaN
19,Bicycle traffic,0.024624,0.002265,0.028125,0.012233,0.035245
20,Proximity to charging stations,0.021615,0.023478,0.017916,0.018665,0.032634
21,Bike lane availability,0.019874,0.015973,0.018931,0.033345,0.026631
22,Surveillance coverage (CCTV),0.018822,0.031356,0.015805,0.017701,0.030862
23,"Existence of shade (e.g., trees)",0.011616,0.004447,0.010351,0.033296,NaN

In [8]:
# round to 3 decimals, take absolute value, and convert to string. then replace nan with '-'
all_weights['Industry'] = all_weights['Industry'].apply(lambda x: f"{abs(x):.3f}" if pd.notnull(x) else '-')
all_weights['Academia'] = all_weights['Academia'].apply(lambda x: f"{abs(x):.3f}" if pd.notnull(x) else '-')
all_weights['Other'] = all_weights['Other'].apply(lambda x: f"{abs(x):.3f}" if pd.notnull(x) else '-')
all_weights['Trashbot'] = all_weights['Trashbot'].apply(lambda x: f"{abs(x):.3f}" if pd.notnull(x) else '-')
all_weights['All'] = all_weights['All'].apply(lambda x: f"{abs(x):.3f}" if pd.notnull(x) else '-')

In [9]:
all_weights

,Feature,All,Industry,Academia,Other,Trashbot
0,Pedestrian density,0.073,0.057,0.074,0.098,0.120
1,Crowd dynamics - purpose with which people nav...,0.063,0.049,0.070,0.057,0.100
2,Pedestrian flow,0.063,0.072,0.064,0.059,-
3,Surface condition,0.057,0.076,0.055,0.018,0.102
4,Intersection safety,0.057,0.056,0.054,0.031,-
5,"Density of street furniture (e.g. garbage, poles)",0.054,0.053,0.057,0.043,0.084
6,Sidewalk width,0.053,0.053,0.055,0.052,0.083
7,Weather conditions,0.051,0.046,0.062,0.024,-
8,Wireless communication infrastructure (e.g. 5G...,0.049,0.054,0.037,0.097,0.069
9,Curb ramp availability,0.048,0.028,0.052,0.039,0.082
10,Sidewalk / Surface roughness,0.041,0.049,0.039,0.037,0.053
11,GPS signal strength,0.040,0.050,0.034,0.049,0.059
12,Local attitudes towards robots,0.039,0.040,0.040,0.071,-
13,Existence of detailed digital maps of the area,0.039,0.052,0.037,0.037,0.061
14,Traffic management systems,0.038,0.051,0.038,0.035,-
15,Vehicle traffic,0.037,0.047,0.039,0.027,-
16,Slope gradient (i.e. elevation change),0.037,0.021,0.043,0.033,0.063
17,Zoning laws and regulation,0.035,0.024,0.039,0.068,-
18,Street lighting,0.026,0.045,0.021,0.008,-
19,Bicycle traffic,0.025,0.002,0.028,0.012,0.035
20,Proximity to charging stations,0.022,0.023,0.018,0.019,0.033
21,Bike lane availability,0.020,0.016,0.019,0.033,0.027
22,Surveillance coverage (CCTV),0.019,0.031,0.016,0.018,0.031
23,"Existence of shade (e.g., trees)",0.012,0.004,0.010,0.033,-

In [10]:
# add in betweeen cols for 'Industry' 'Academia' and 'Trashbot' that have an up arrow if the value is higher than the 'All' value, and a down arrow if it is lower
def add_arrows_to_col(row, col_name):
    if row[col_name] == '-':
        return '-'
    if row[col_name] > row['All']:
        return r"\textcolor{green}{↑}" + f" {row[col_name]}"
    elif row[col_name] < row['All']:
        return r"\textcolor{red}{↓}" + f" {row[col_name]}"

    else:
        return r"$-$" + f" {row[col_name]}"

all_weights['Industry'] = all_weights.apply(lambda x: add_arrows_to_col(x, 'Industry'), axis=1)
all_weights['Academia'] = all_weights.apply(lambda x: add_arrows_to_col(x, 'Academia'), axis=1)
all_weights['Other'] = all_weights.apply(lambda x: add_arrows_to_col(x, 'Other'), axis=1)

In [11]:
all_weights

,Feature,All,Industry,Academia,Other,Trashbot
0,Pedestrian density,0.073,\textcolor{red}{↓} 0.057,\textcolor{green}{↑} 0.074,\textcolor{green}{↑} 0.098,0.120
1,Crowd dynamics - purpose with which people nav...,0.063,\textcolor{red}{↓} 0.049,\textcolor{green}{↑} 0.070,\textcolor{red}{↓} 0.057,0.100
2,Pedestrian flow,0.063,\textcolor{green}{↑} 0.072,\textcolor{green}{↑} 0.064,\textcolor{red}{↓} 0.059,-
3,Surface condition,0.057,\textcolor{green}{↑} 0.076,\textcolor{red}{↓} 0.055,\textcolor{red}{↓} 0.018,0.102
4,Intersection safety,0.057,\textcolor{red}{↓} 0.056,\textcolor{red}{↓} 0.054,\textcolor{red}{↓} 0.031,-
5,"Density of street furniture (e.g. garbage, poles)",0.054,\textcolor{red}{↓} 0.053,\textcolor{green}{↑} 0.057,\textcolor{red}{↓} 0.043,0.084
6,Sidewalk width,0.053,$-$ 0.053,\textcolor{green}{↑} 0.055,\textcolor{red}{↓} 0.052,0.083
7,Weather conditions,0.051,\textcolor{red}{↓} 0.046,\textcolor{green}{↑} 0.062,\textcolor{red}{↓} 0.024,-
8,Wireless communication infrastructure (e.g. 5G...,0.049,\textcolor{green}{↑} 0.054,\textcolor{red}{↓} 0.037,\textcolor{green}{↑} 0.097,0.069
9,Curb ramp availability,0.048,\textcolor{red}{↓} 0.028,\textcolor{green}{↑} 0.052,\textcolor{red}{↓} 0.039,0.082
10,Sidewalk / Surface roughness,0.041,\textcolor{green}{↑} 0.049,\textcolor{red}{↓} 0.039,\textcolor{red}{↓} 0.037,0.053
11,GPS signal strength,0.040,\textcolor{green}{↑} 0.050,\textcolor{red}{↓} 0.034,\textcolor{green}{↑} 0.049,0.059
12,Local attitudes towards robots,0.039,\textcolor{green}{↑} 0.040,\textcolor{green}{↑} 0.040,\textcolor{green}{↑} 0.071,-
13,Existence of detailed digital maps of the area,0.039,\textcolor{green}{↑} 0.052,\textcolor{red}{↓} 0.037,\textcolor{red}{↓} 0.037,0.061
14,Traffic management systems,0.038,\textcolor{green}{↑} 0.051,$-$ 0.038,\textcolor{red}{↓} 0.035,-
15,Vehicle traffic,0.037,\textcolor{green}{↑} 0.047,\textcolor{green}{↑} 0.039,\textcolor{red}{↓} 0.027,-
16,Slope gradient (i.e. elevation change),0.037,\textcolor{red}{↓} 0.021,\textcolor{green}{↑} 0.043,\textcolor{red}{↓} 0.033,0.063
17,Zoning laws and regulation,0.035,\textcolor{red}{↓} 0.024,\textcolor{green}{↑} 0.039,\textcolor{green}{↑} 0.068,-
18,Street lighting,0.026,\textcolor{green}{↑} 0.045,\textcolor{red}{↓} 0.021,\textcolor{red}{↓} 0.008,-
19,Bicycle traffic,0.025,\textcolor{red}{↓} 0.002,\textcolor{green}{↑} 0.028,\textcolor{red}{↓} 0.012,0.035
20,Proximity to charging stations,0.022,\textcolor{green}{↑} 0.023,\textcolor{red}{↓} 0.018,\textcolor{red}{↓} 0.019,0.033
21,Bike lane availability,0.020,\textcolor{red}{↓} 0.016,\textcolor{red}{↓} 0.019,\textcolor{green}{↑} 0.033,0.027
22,Surveillance coverage (CCTV),0.019,\textcolor{green}{↑} 0.031,\textcolor{red}{↓} 0.016,\textcolor{red}{↓} 0.018,0.031
23,"Existence of shade (e.g., trees)",0.012,\textcolor{red}{↓} 0.004,\textcolor{red}{↓} 0.010,\textcolor{green}{↑} 0.033,-

In [12]:
# produce pretty latex table 
os.makedirs('../chi24_roving_whiteboards/tables', exist_ok=True)
all_weights.to_latex('../chi24_roving_whiteboards/tables/feature_weights.tex', index=False)